/*
 * StarterKit.
 */
package io.codeffeine.starterkit.usecase.mailing;

import io.codeffeine.starterkit.domain.mailing.contract.SendEmailInterface;
import io.codeffeine.starterkit.domain.mailing.entity.Email;
import io.codeffeine.starterkit.usecase.adapter.mailing.MailingAdapter;
import com.google.inject.Inject;

/**
 *
 * @author Mirko Gueregat @mgueregath <mgueregath@codeffeine.io>
 */
public class SendEmail implements SendEmailInterface {

    private final MailingAdapter emailService;

    @Inject
    public SendEmail(MailingAdapter emailService) {
        this.emailService = emailService;
    }

    @Override
    public void send(Email email) {
        String template = "<!DOCTYPE html>\n"
                + "<html xmlns='http://www.w3.org/1999/xhtml'>\n"
                + "\n"
                + "<head>\n"
                + "  <meta charset='utf-8'>\n"
                + "  <meta name='viewport' content='width=device-width'>\n"
                + "  <meta http-equiv='X-UA-Compatible' content='IE=edge'>\n"
                + "  <meta name='x-apple-disable-message-reformatting'>\n"
                + "  <title></title>\n"
                + "\n"
                + "  <style>\n"
                + "    html,\n"
                + "    body {\n"
                + "      margin: 0 auto !important;\n"
                + "      padding: 0 !important;\n"
                + "      height: 100% !important;\n"
                + "      width: 100% !important;\n"
                + "    }\n"
                + "\n"
                + "    * {\n"
                + "      -ms-text-size-adjust: 100%;\n"
                + "      -webkit-text-size-adjust: 100%;\n"
                + "    }\n"
                + "\n"
                + "    div[style*='margin: 16px 0'] {\n"
                + "      margin: 0 !important;\n"
                + "    }\n"
                + "\n"
                + "    table,\n"
                + "    td {\n"
                + "      mso-table-lspace: 0pt !important;\n"
                + "      mso-table-rspace: 0pt !important;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      border-spacing: 0 !important;\n"
                + "      border-collapse: collapse !important;\n"
                + "      table-layout: fixed !important;\n"
                + "      margin: 0 auto !important;\n"
                + "    }\n"
                + "\n"
                + "    table table table {\n"
                + "      table-layout: auto;\n"
                + "    }\n"
                + "\n"
                + "    img {\n"
                + "      -ms-interpolation-mode: bicubic;\n"
                + "    }\n"
                + "\n"
                + "    *[x-apple-data-detectors] {\n"
                + "      color: inherit !important;\n"
                + "      text-decoration: none !important;\n"
                + "    }\n"
                + "\n"
                + "    .x-gmail-data-detectors,\n"
                + "    .x-gmail-data-detectors *,\n"
                + "    .aBn {\n"
                + "      border-bottom: 0 !important;\n"
                + "      cursor: default !important;\n"
                + "    }\n"
                + "\n"
                + "    .button-link {\n"
                + "      text-decoration: none !important;\n"
                + "    }\n"
                + "\n"
                + "    #team {\n"
                + "      text-align: right;\n"
                + "      font-weight: 600;\n"
                + "      font-style: italic;\n"
                + "    }\n"
                + "\n"
                + "    #td-content {\n"
                + "      text-justify: auto;\n"
                + "    }\n"
                + "\n"
                + "    @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\n"
                + "      /* iPhone 6 and 6+ */\n"
                + "      .email-container {\n"
                + "        min-width: 375px !important;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "  <style>\n"
                + "    .button-td,\n"
                + "    .button-a {\n"
                + "      transition: all 100ms ease-in;\n"
                + "    }\n"
                + "\n"
                + "    .button-td:hover,\n"
                + "    .button-a:hover {\n"
                + "      background: #3c5e00 !important;\n"
                + "      border-color: #3c5e00 !important;\n"
                + "    }\n"
                + "\n"
                + "    @media screen and (max-width: 480px) {\n"
                + "      .fluid {\n"
                + "        width: 100% !important;\n"
                + "        max-width: 100% !important;\n"
                + "        height: auto !important;\n"
                + "        margin-left: auto !important;\n"
                + "        margin-right: auto !important;\n"
                + "      }\n"
                + "      .stack-column,\n"
                + "      .stack-column-center {\n"
                + "        display: block !important;\n"
                + "        width: 100% !important;\n"
                + "        max-width: 100% !important;\n"
                + "        direction: ltr !important;\n"
                + "      }\n"
                + "      .stack-column-center {\n"
                + "        text-align: center !important;\n"
                + "      }\n"
                + "      .center-on-narrow {\n"
                + "        text-align: center !important;\n"
                + "        display: block !important;\n"
                + "        margin-left: auto !important;\n"
                + "        margin-right: auto !important;\n"
                + "        float: none !important;\n"
                + "      }\n"
                + "      table.center-on-narrow {\n"
                + "        display: inline-block !important;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body width='100%' bgcolor='#222222' style='margin: 0; mso-line-height-rule: exactly;'>\n"
                + "  <center style='width: 100%; background: #EEEEEE;'>\n"
                + "    <div style='display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;'>\n"
                + "      \n"
                + "    </div>\n"
                + "    <div style='max-width: 680px; margin: auto;' class='email-container'>\n"
                + "      <table role='presentation' cellspacing='0' cellpadding='0' border='0' align='center' width='100%' style='max-width: 680px;'>\n"
                + "        <tr>\n"
                + "          <td style='padding: 20px 0; text-align: center'>\n"
                + "          </td>\n"
                + "        </tr>\n"
                + "      </table>\n"
                + "      <table role='presentation' cellspacing='0' cellpadding='0' border='0' align='center' width='100%' style='max-width: 680px;'>\n"
                + "        <tr>\n"
                + "          <td bgcolor='#653665' style='padding: 0 10px;'>\n"
                + "            <center>\n"
                + "              <img src='' width='200' height='' alt='alt_text' border='0' align='center' class='fluid' style='width: 100%; max-width: 400px; height: auto; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555; align-content: center; margin-top: 35px; margin-bottom: 35px;'>\n"
                + "            </center>\n"
                + "          </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "          <td bgcolor='#ffffff'>\n"
                + "            <table role='presentation' cellspacing='0' cellpadding='0' border='0' width='100%'>\n"
                + "              <tr>\n"
                + "                <td id=\"td-content\" style='padding: 40px; text-align: justify; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;'>\n"
                + "                  Estimado " + email.getName() + ",\n"
                + "                  <br>\n"
                + "                  <br>\n"
                + email.getContent()
                + "                  <br>\n"
                + "                  <br>\n"
                + "                  Le saluda atentamente,\n"
                + "                  <br>\n"
                + "                  <p id=\"team\">Codeffeine SpA.</p>\n"
                + "                  \n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </table>\n"
                + "          </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "          <td bgcolor='#653665' valign='middle' style='text-align: center; background-position: center center !important; background-size: cover !important; font-style: italic;'>\n"
                + "\n"
                + "            <div>\n"
                + "              <table role='presentation' border='0' cellpadding='0' cellspacing='0' align='center' width='100%' style='max-width:500px; margin: auto;'>\n"
                + "                <tr>\n"
                + "                  <td valign='middle' style='text-align: center; padding: 40px 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #ffffff;'>\n"
                + "                    Codeffeine\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </div>\n"
                + "\n"
                + "          </td>\n"
                + "        </tr>\n"
                + "      </table>\n"
                + "      <table role='presentation' cellspacing='0' cellpadding='0' border='0' align='center' width='100%' style='max-width: 680px;'>\n"
                + "        <tr>\n"
                + "          <td style='padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; line-height:18px; text-align: center; color: #888888;'\n"
                + "            class='x-gmail-data-detectors'>\n"
                + "            <br>\n"
                + "            <br>Codeffeine SpA - 2018\n"
                + "            <br>Valdivia, Región de Los Ríos, Chile.\n"
                + "            <br>contacto@codeffeine.io\n"
                + "          </td>\n"
                + "        </tr>\n"
                + "    </div>\n"
                + "  </center>\n"
                + "</body>\n"
                + "</html>";
        email.setContent(template);
        Thread t = new Thread(() -> emailService.send(email));
        t.start();
    }
}
